# Generated by Django 3.1.4 on 2021-01-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
