# Generated by Django 3.1.4 on 2020-12-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_card',
        ),
    ]
