# Generated by Django 3.1.4 on 2020-12-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_card',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
