# Generated by Django 3.1.4 on 2020-12-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_card',
            field=models.ImageField(upload_to=''),
        ),
    ]
